# Generated by Django 3.1.3 on 2020-12-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipemanager', '0002_auto_20201130_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_unit_id', to='recipemanager.unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_type',
            field=models.CharField(choices=[('gm/kg', 'Gram/Kilogram'), ('ml/l', 'MilliLitre/Litre')], default='Select unit type', max_length=64),
        ),
    ]
