# Generated by Django 3.1.3 on 2020-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemanager', '0003_auto_20201202_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
