# Generated by Django 3.1.3 on 2020-12-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemanager', '0004_auto_20201202_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='unit',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
