# Generated by Django 3.1.3 on 2020-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemanager', '0006_remove_item_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='base_unit',
            field=models.CharField(choices=[('gm', 'Gram'), ('ml', 'MilliLitre')], default='Select base unit', max_length=40),
        ),
    ]
